import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Zain, Afacad } from "next/font/google";

const zain = Zain({
  subsets: ["latin"],
  weight: ["700", "900"],
  variable: '--font-zain',
  display: 'swap',
});

const afacad = Afacad({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: '--font-afacad',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn(zain.variable, afacad.variable)}>
      <body className="antialiased bg-neutral-50 font-sans">
        {children}
      </body>
    </html>
  );
}
